[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_mint_sell_nft = "H4cywKiiWQK9ShnEzQ7e2L3yXMgms2tcmPmPXciZsP5v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/hyperion/test-keypair.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-mint-spltoken = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint-spltoken.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"

